// @flow

export default {
  // title
  titletext: require('./assets/titletext.png'),
  cloud1: require('./assets/cloud1.png'),
  titlebusbody: require('./assets/titlebusbody.png'),
  titlebuswheels1: require('./assets/titlebuswheels1.png'),
  titlebuswheels2: require('./assets/titlebuswheels2.png'),
  sky: require('./assets/sky.png'),
  titlesand: require('./assets/titlesand.png'),
  // game
  dssand2dark: require('./assets/dssand2darkgrey1x.png'),
  dssand2: require('./assets/dssand21x.png'),
  dstent: require('./assets/dstent.png'),
  dstentdmg: require('./assets/dstentdmg.png'),
  cheese: require('./assets/cheese.png'),
  water: require('./assets/water2.png'),
  tequila: require('./assets/tequila.png'),
  guystill: require('./assets/guystill.png'),
  guywalkcycle1: require('./assets/guywalkcycle1.png'),
  guywalkcycle2: require('./assets/guywalkcycle2.png'),
  guywalkcycle3: require('./assets/guywalkcycle3.png'),
  personstill: require('./assets/personstill.png'),
  personwalkcycle1: require('./assets/personwalkcycle1.png'),
  personwalkcycle2: require('./assets/personwalkcycle2.png'),
  personwalkcycle3: require('./assets/personwalkcycle3.png'),
  target: require('./assets/target.png'),
  pissed: require('./assets/pissed.png'),
  occupied: require('./assets/occupied.png'),
  bus: require('./assets/bus.png'),
  bg: require('./assets/bg.png'),
  smoke1: require('./assets/smoke1.png'),
  smoke2: require('./assets/smoke2.png'),
  smoke3: require('./assets/smoke3.png'),
  plus100: require('./assets/100.png'),
  owned: require('./assets/owned.png'),
};
