export default {
  dstent: require('./assets/dstent.png'),
  dstentdmg: require('./assets/dstentdmg.png'),
  cheese: require('./assets/cheese.png'),
  water: require('./assets/water2.png'),
  guystill: require('./assets/guystill.png'),
  guywalkcycle1: require('./assets/guywalkcycle1.png'),
  guywalkcycle2: require('./assets/guywalkcycle2.png'),
  guywalkcycle3: require('./assets/guywalkcycle3.png'),
  personstill: require('./assets/personstill.png'),
  personwalkcycle1: require('./assets/personwalkcycle1.png'),
  personwalkcycle2: require('./assets/personwalkcycle2.png'),
  personwalkcycle3: require('./assets/personwalkcycle3.png'),
  target: require('./assets/target.png'),
};
